FROM kilna/liquibase-postgres
ENV LIQUIBASE_HOST="35.205.28.224"
ENV LIQUIBASE_DATABASE=devconapp
ENV LIQUIBASE_USERNAME=devconapp
ENV LIQUIBASE_PASSWORD=Bp9TJ5L7mkkEgH9N
ENV CLASSPATH='/opt/jdbc/postgres-jdbc.jar'
COPY mychangelog.xml /workspace/changelog.xml
